global:
  scrape_interval:     60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["192.168.1.101:9093"]
rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.1.101:9090']
        labels:
          instance: prometheus
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.101:9100']
        labels:
          instance: node
